# Netlify instructions to control build

[build]
  command = "hugo --gc --minify"
  # see also https://discourse.gohugo.io/t/hugo-build-error-with-gc-minify/20600/14

[context.production.environment]
  HUGO_VERSION = "0.75.1" # substitute whichever version you prefer; this was as of 2020-08-07
  HUGO_ENV = "production"
  