# Netlify instructions to control build

[build]
  command = "hugo --gc --minify"
  # see also https://discourse.gohugo.io/t/hugo-build-error-with-gc-minify/20600/14

[context.production.environment]
  HUGO_VERSION = "0.81.0" # substitute whichever version you prefer
  HUGO_ENV = "production"
  